# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kyle Stratis
tagline:             'Software Developer at Aderant'
description:         'On an eternal quest to build and learn'
url:                 http://kylestratis.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:             Kyle Stratis
  github:           kylestratis
  email:            kylestratis@gmail.com
  linkedin:         kylestratis
  goodreads:        kylestratis
  google_scholar:   http://scholar.google.com/citations?hl=en&user=-WO2ezMAAAAJ

# Custom vars
version:             1.0.0
